/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  projectsSidebar: [
    {
      type: 'doc',
      id: 'intro',
    },
    // {
    //   type: 'category',
    //   label: 'Over Engineering',
    //   link: {
    //     type: 'doc',
    //     id: 'over-engineering/over-engineering-overview',
    //   },
    //   items: [
    //     {
    //       type: 'autogenerated',
    //       dirName: 'over-engineering',
    //     },
    //   ],
    // },
    // {
    //   type: 'category',
    //   label: 'Finreg.sg',
    //   link: {
    //     type: 'doc',
    //     id: 'finreg/finreg-overview',
    //   },
    //   items: [
    //     {
    //       type: 'autogenerated',
    //       dirName: 'finreg',
    //     },
    //   ],
    // },
    // {
    //   type: 'category',
    //   label: 'Chinholin.com',
    //   link: {
    //     type: 'doc',
    //     id: 'chinholin/chinholin-overview',
    //   },
    //   items: [
    //     {
    //       type: 'autogenerated',
    //       dirName: 'chinholin',
    //     },
    //   ],
    // },
    // {
    //   type: 'category',
    //   label: 'Dotfiles',
    //   link: {
    //     type: 'doc',
    //     id: 'dotfiles/dotfiles-overview',
    //   },
    //   items: [
    //     {
    //       type: 'autogenerated',
    //       dirName: 'dotfiles',
    //     },
    //   ],
    // },
  ],
};

module.exports = sidebars;
